Repository Pixel-Power/Pixstar-guide, pull requests merged in 2024-03, with the labels that each got.

#1 [FEATURE][MAIN][반응형 Navbar 생성(토글 생성전)]
  package-lock.json
  package.json
  src/App.js
  src/Layouts/Layout1.js
  src/components/Navbar.js
  src/components/Navbar.module.css
  src/components/Sidebar.js
  src/components/Sidebar.module.css
Labels: feature

#2 [FEATURE][RESTAURANT][레스토랑 서치 결과]
  public/img/img13.jpg
  public/img/img14.jpg
  public/img/img15.jpg
  public/img/img16.jpg
  public/img/img17.jpg
  public/img/img18.jpg
  src/App.js
  src/Pages/Restaurant-detail.js
  src/Pages/Restaurant-search-result.js
  src/Pages/Restaurant-search-result.module.css
  src/apis/RestaurantAPI.js
  src/data/resDetail.json
Labels: feature

#9 [FEATURE][MAIN][Body Box 레이아웃 및 형상 초기 구현]
  public/images/영차 떡볶이.png
  public/images/이달의 식당.jpg
  src/App.js
  src/Pages/Main.js
  src/Pages/Main.module.css
Labels: feature

#11 [FEATURE][LOGIN]로그인 기능 구현
  src/App.js
  src/Pages/Company-info.js
  src/Pages/Error.js
  src/Pages/Login.js
  src/Pages/Main.js
  src/Pages/Md.js
  src/Pages/Mypage-memberout.js
  src/apis/MemAPI.js
  src/components/Footer.js
  src/components/Footer.module.css
Labels: feature

#12 [FEATURE][HAEDER][헤더 생성]
  public/images/header-images/Add User Male.png
  public/images/header-images/Home.png
  public/images/header-images/Login.png
  public/images/header-images/Logout Rounded.png
  public/images/header-images/Search.png
  public/images/header-images/pixstar-guide-logo.png
  src/App.js
  src/components/Header1.js
  src/components/Header1.module.css
  src/components/Header2.js
  src/components/Header2.module.css
Labels: feature

#17 [FEATURE][MAIN][반응형 Navbar 생성2]
  src/Layouts/Layout1.js
  src/components/Sidebar.js
  src/components/Sidebar.module.css
  src/components/SidebarItem.js
  src/components/SidebarToggle.js
Labels: feature

#22 [FEATURE][RESTAURANT][MAIN][레스토랑검색결과, 네브바 변경]
  public/img/3star.png
  public/img/location.png
  public/img/phone.png
  src/App.js
  src/Layouts/Layout1.js
  src/Pages/Restaurant-search-result.js
  src/Pages/Restaurant-search-result.module.css
  src/components/Sidebar.js
  src/components/Sidebar.module.css
  src/components/Sidebar1.js
  src/components/Sidebar1.module.css
  src/components/SidebarItem.js
  src/components/SidebarToggle.js
Labels: feature

#38 [FEATURE][RESTAURANT][상세조회페이지 예약기능 구현]
  package-lock.json
  package.json
  public/images/restaurant-detail/calendar.png
  src/Pages/MyPage.module.css
  src/Pages/Restaurant-detail.js
  src/Pages/Restaurant-detail.module.css
  src/components/CalendarModal.js
  src/components/CalendarModal.module.css
Labels: feature

#31 [FEATURE][RESERVATIONDETAIL][예약정보확인창]
  public/images/food/chinesefood/chinesefood (13).jpg
  src/App.js
  src/Pages/MyPage-reservation-detail.js
  src/Pages/MyPage-reservation-detail.module.css
  src/Pages/MyPage-reservation.module.css
  src/Pages/MyPage.js
  src/Pages/MyPage.module.css
Labels: documentation, feature

#42 [FEATURE][LOGIN]로그인 기능 구현4
  src/Pages/Login.js
  src/Pages/SignUp.js
Labels: feature

#51 [FEATURE][RESTAURANT]예약내역페이지로 이동
  src/Pages/MyPage-reservation-detail.js
  src/Pages/Restaurant-detail.js
  src/apis/MapAPI.js
  src/apis/MemAPI.js
  src/components/CalendarModal.js
  src/components/CalendarModal.module.css
Labels: feature

#52 [FEATURE][LOGIN]로그인 기능 구현5
  src/App.js
  src/Layouts/Layout2.js
  src/Pages/Login.js
  src/Pages/Logout.js
  src/Pages/Logout.module.css
  src/apis/MemAPI.js
  src/components/Header2.js
Labels: feature

#54 [FEATURE][RESTAURANT] 상세 조회 페이지 캘린더 및 지도 기능 추가
  src/Pages/Restaurant-detail.js
  src/Pages/Restaurant-detail.module.css
  src/components/CalendarModal.js
  src/components/CalendarModal.module.css
Labels: feature

#56 [FEATURE][RESERVATION][마이페이지 리스트, 예약 상세정보 기능 추가]
  src/App.js
  src/Pages/MyPage-reservation-detail.js
  src/Pages/MyPage-reservation.js
  src/Pages/MyPage-reservation.module.css
  src/Pages/MyPage.js
Labels: documentation, feature

#58 [FEATURE][MAIN][mainPage 레이아웃 및 header,footer 레이아웃 설정 작업]
  public/images/food/errorPage-images/image.png
  public/images/mainPage-images/search-icon.png
  public/images/mainPage-images/검색창배경.png
  public/images/mainPage-images/구글검색1위 .png
  public/images/mainPage-images/영차 떡볶이.png
  public/images/mainPage-images/오늘의레시피.png
  public/images/mainPage-images/이달의 식당.jpg
  public/images/mainPage-images/체험단.png
  public/images/mainPage-images/커피의효능.png
  src/App.js
  src/Pages/Error.js
  src/Pages/Main.js
  src/Pages/Main.module.css
  src/components/Footer.js
  src/components/Footer.module.css
  src/components/Header1.module.css
  src/components/Header2.module.css
Labels: feature

#59 [FEATURE][LOGIN]로그인 기능 구현6
  src/App.js
  src/Pages/Login.js
  src/Pages/Logout.js
  src/apis/MemAPI.js
  src/components/UserItem.js
Labels: feature

#64 [FEATURE][LOGIN]로그인 기능 구현9
  src/App.js
  src/Pages/Login.js
  src/Pages/MyPage-reservation-detail.js
  src/Pages/MyPage-reservation.js
  src/Pages/MyPage.js
  src/apis/MemAPI.js
  src/components/UserItem.js
Labels: feature

#70 [FEATURE][RESTAURANT]상세페이지 로그인 여부 확인
  package-lock.json
  package.json
  src/App.js
  src/Layouts/Layout4.js
  src/Pages/Login.js
  src/Pages/Restaurant-detail.js
  src/apis/MemAPI.js
  src/components/CalendarModal.js
  src/data/resDetail.json
Labels: feature

#73 mypage 레이아웃 변경, 예약 상세페이지 수정 중
  src/App.js
  src/Pages/MyPage-reservation-detail.js
  src/Pages/MyPage-reservation.js
  src/apis/MapAPI.js
  src/apis/MemAPI.js
  src/apis/RSVAPI.js
  src/components/CalendarModal.js
  src/components/Header1.js
  src/components/Header2.js
  src/components/UserItem.js
  src/data/reservation.json
Labels: documentation, feature

#71 [FEATURE][RESTAURANT][레스토랑검색결과페이지 -> 식당 상세페이지로 이동]
  public/images/food/koreanfood/koreanfood (17).jpg
  public/images/food/koreanfood/koreanfood (18).jpg
  src/App.js
  src/Pages/Restaurant-detail.js
  src/Pages/Restaurant-detail.module.css
  src/Pages/Restaurant-search-result.js
  src/apis/RestaurantAPI.js
  src/components/CalendarModal.js
  src/components/RestaurantItem.js
  src/data/resDetail.json
Labels: feature

#67 [FEATURE][MAIN, SITEMAP, USERTERM, COMPANYINFO, PRIVACY][CSS 설정 및 링크 연결]
  public/images/mainPage-images/구글검색1위.png
  src/App.js
  src/Pages/Company-info.js
  src/Pages/Main.js
  src/Pages/Main.module.css
  src/Pages/Privacy.js
  src/Pages/SitMap.module.css
  src/Pages/SiteMap.js
  src/Pages/SiteMap.module.css
  src/Pages/UTPV.module.css
  src/Pages/UseTerm.module.css
  src/Pages/UseTerms.js
  src/components/Footer.js
  src/components/Footer.module.css
  src/components/Header1.module.css
  src/components/Header2.module.css
  src/components/Sidebar1.module.css
Labels: feature

#77 [FEATURE][MAIN][SEARCH BAR 설정]
  src/Pages/Main.js
  src/Pages/Restaurant-search-result.js
  src/components/Header1.module.css
  src/components/Header2.module.css
  src/components/Sidebar1.module.css
Labels: feature

#76 [FEATURE][RESERATIONDETAILFAKE][마이페이지 예약상세페이지]
  src/App.js
  src/Pages/MyPage-reservation-detail-fake.js
  src/Pages/MyPage-reservation-detail-fake.module.css
  src/Pages/MyPage-reservation.js
Labels: feature

#80 [FEATURE][EDITREVIEW][리뷰 내용 수정]
  public/images/myPage-images/1STAR.png
  public/images/myPage-images/2STAR.png
  public/images/myPage-images/3STAR.png
  public/images/myPage-images/4STAR.png
  src/App.js
  src/Pages/MyPage.js
Labels: documentation

#85 [FEATURE][POPUP][MD팝업창]
  public/images/company-info/MD팝업.png
  src/App.js
  src/Pages/Main.js
  src/Pages/Md.js
  src/Pages/MyPage-reservation.js
Labels: feature

#90 [FEATURE][LOGIN]로그인 기능 구현10
  src/Pages/Login.js
  src/Pages/Login.module.css
  src/Pages/Restaurant-detail.js
  src/Pages/Restaurant-search-result.js
  src/Pages/SignUp.js
  src/apis/MemAPI.js
  src/apis/RestaurantAPI.js
Labels: feature

#89 [FEATURE][RESTAURANT]상세페이지 내용 추가
  public/images/restaurant-detail/bookmark.png
  public/images/restaurant-detail/like.png
  public/images/restaurant-detail/review.png
  public/images/restaurant-detail/review1.jpg
  public/images/restaurant-detail/review2.jpg
  public/images/restaurant-detail/review3.jpg
  public/images/restaurant-detail/review4.jpg
  public/images/restaurant-detail/review5.jpg
  src/App.js
  src/Pages/Restaurant-detail.js
  src/Pages/Restaurant-detail.module.css
  src/Pages/Restaurant-search-result.js
  src/components/CalendarModal.js
  src/components/CalendarModal.module.css
Labels: feature

#84 [FEATURE][MAIN, HEADER, FOOTER, SITEMAP][여러 CSS 설정 및 사이트맵 링크연결]
  src/App.js
  src/Pages/Company-info.js
  src/Pages/Main.js
  src/Pages/Main.module.css
  src/Pages/MyPage-reservation-detail-fake.module.css
  src/Pages/MyPage-reservation-detail.module.css
  src/Pages/MyPage-reservation.module.css
  src/Pages/MyPage.module.css
  src/Pages/Restaurant-detail.js
  src/Pages/Restaurant-detail.module.css
  src/Pages/Restaurant-search-result.module.css
  src/Pages/SiteMap.js
  src/Pages/SiteMap.module.css
  src/Pages/UTPV.module.css
  src/components/Header1.js
  src/components/Header1.module.css
  src/components/Header2.js
  src/components/Header2.module.css
Labels: feature

#87 [FEATURE,DEVELOP][MAIN,RESTAURANT][메인 css 변경 / 메인화면에서 카테고리 검색 이동]
  public/images/mainPage-images/이달의 식당2.png
  public/images/mainPage-images/이달의 식당3.jpg
  public/images/mainPage-images/픽스타 매거진.jpeg
  src/App.js
  src/Pages/Main.js
  src/Pages/Main.module.css
  src/Pages/Restaurant-search-result.js
  src/Pages/Restaurant-search-result.module.css
Labels: feature, develop

#92 [FEATURE][RESTAURANT,MAIN][검색결과출력 기능 구현 및 메인화면 CSS 변경]
  package-lock.json
  package.json
  public/images/mainPage-images/1.jpg
  public/images/mainPage-images/2.jpg
  public/images/mainPage-images/3.jpg
  public/images/mainPage-images/wine1.jpg
  public/images/mainPage-images/wine2.jpg.jpg
  public/images/mainPage-images/이달의 식당4.png
  public/images/mainPage-images/포스터.png
  src/Pages/Main.js
  src/Pages/Main.module.css
  src/Pages/Restaurant-search-result.js
  src/Pages/Restaurant-search-result.module.css
  src/components/Sidebar1.js
  src/components/Sidebar1.module.css
  src/data/resDetail.json
Labels: feature, develop

#93 [DEVELOPE][HEADER,MAIN][usercode 및 main.css 변경]
  src/Pages/Main.js
  src/Pages/Main.module.css
  src/components/Header2.js
Labels: develop

#103 [FEATURE][RESTAURANT & MYPAGE] 식당상세페이지 지도 흰 화면으로 뜨는 이슈 & 예약상세페이지와 연결
  public/images/food/japanesefood/japanesefood (13).jpg
  public/images/food/japanesefood/japanesefood (14).jpg
  public/images/food/japanesefood/japanesefood (15).jpg
  public/images/food/koreanfood/koreanfood (19).jpg
  public/images/food/koreanfood/koreanfood (20).jpg
  public/index.html
  src/App.js
  src/Pages/MyPage-reservation-detail.js
  src/Pages/MyPage-reservation.js
  src/Pages/MyPage.js
  src/Pages/Mypage-reservation-test.js
  src/Pages/Mypage-reservation-test.module.css
  src/Pages/Restaurant-detail.js
  src/Pages/Restaurant-detail.module.css
  src/components/CalendarModal.module.css
  src/components/Map.js
  src/components/ReservationItem.js
  src/components/ReservationItem.module.css
  src/data/resDetail.json
  src/data/reservation.json
Labels: bug, feature

#102 [FEATURE][MAIN, HEADER, FOOTER 등][마이페이지 로그인 경고창, CSS조정 등]
  src/App.js
  src/Pages/Login.js
  src/Pages/Logout.module.css
  src/Pages/MyPage-reservation-detail-fake.js
  src/Pages/MyPage-reservation-detail-fake.module.css
  src/Pages/MyPage-reservation-detail.module.css
  src/Pages/MyPage-reservation.module.css
  src/Pages/MyPage.module.css
  src/Pages/Restaurant-detail.module.css
  src/Pages/SiteMap.js
  src/Pages/SiteMap.module.css
  src/Pages/UTPV.module.css
  src/components/Footer.js
  src/components/Footer.module.css
  src/components/Header1.js
  src/components/Header1.module.css
  src/components/Header2.js
  src/components/Header2.module.css
  src/components/Sidebar1.module.css
Labels: feature

#100 [FEATURE][MAIN][사이드바 해시태그 클릭 시 해당 카테고리 이동, 이달의 식당 페이지이동, main css 수정]
  src/Pages/Main.js
  src/Pages/Main.module.css
  src/Pages/Restaurant-search-result.js
  src/Pages/Restaurant-search-result.module.css
  src/components/Header1.module.css
  src/components/Header2.module.css
  src/components/Sidebar1.js
  src/components/Sidebar1.module.css
Labels: feature, develop
