Repository Pixel-Power/Pixstar-guide, pull requests merged in 2024-04, with the labels that each got.

#104 [FEATURE][POPUP][MD팝업창]
  src/Pages/Main.js
  src/Pages/Md.js
Labels: documentation

#105 [FEATURE][MAIN, RESTAURANTDETAIL, RESERVATIONDETAIL, LOGIN, LOGOUT][레스토랑,예약 디테일 로그인 헤더 유지 등]
  package-lock.json
  package.json
  public/images/errorPage/image.png
  src/App.js
  src/Pages/Error.js
  src/Pages/Error.module.css
  src/Pages/Login.js
  src/Pages/Login.module.css
  src/Pages/Logout.js
  src/Pages/Logout.module.css
  src/Pages/MyPage-reservation-detail.module.css
  src/Pages/Privacy.js
  src/Pages/Restaurant-detail.js
  src/Pages/Restaurant-detail.module.css
  src/Pages/UTPV.module.css
  src/components/CalendarModal.js
  src/components/CalendarModal.module.css
  src/components/ScrollToTop.js
Labels: feature

#107 [DEVELOPE][MAIN][CSS 변경]
  public/images/mainPage-images/mainbar.png
  public/images/mainPage-images/search-icon2.png
  public/images/mainPage-images/배경1.png
  public/images/mainPage-images/배경2.png
  public/images/mainPage-images/배경3.png
  public/images/mainPage-images/배경4.png
  public/images/mainPage-images/배경5.png
  public/images/mainPage-images/배경6.png
  public/images/mainPage-images/배경7.png
  public/images/mainPage-images/배경8.png
  public/images/mainPage-images/이달의 식당5.png
  public/images/mainPage-images/픽스타 매거진1.png
  public/images/mainPage-images/픽스타 매거진2.png
  public/index.html
  src/App.js
  src/Pages/Login.js
  src/Pages/Login.module.css
  src/Pages/Main.js
  src/Pages/Main.module.css
  src/Pages/Restaurant-search-result.module.css
  src/Pages/SignUp.js
  src/Pages/SignUp.module.css
  src/components/Footer.module.css
  src/components/Sidebar1.module.css
Labels: bug, develop
